"""Lane worker — processes one slice end-to-end against a worktree.

A lane runs in its own thread. The scheduler hands it a slice id; the lane
sets up a clean worktree on a feature branch, spawns the implementer agent,
runs the gates with bounded retries, pushes the branch, and opens the PR.

Phase 2 stops at PR open. The lane marks the slice ``pr_opened`` in its
status JSON; Phase 3 will pick up from there with the reviewer agent.

Failure semantics:

- Gate failure inside ``run_cap`` retries: resume the implementer with a
  retry prompt, re-run gates. Capped by ``cfg.max_retries``.
- Cap exhausted, or agent timed out, or no diff produced → ``failed``.
- Any unhandled exception during PR open → ``failed`` with the exception
  recorded in ``last_error``.

The lane is a normal callable. The scheduler is responsible for actually
spawning a thread per lane.
"""

from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

from .claude import RunResult, parse_verdict, run_implementer, run_reviewer
from .config import NamlConfig
from .gates import run_gates
from . import gitops
from . import prompts
from . import state as state_mod
from . import states
from .package import Slice, Sprint


log = logging.getLogger("naml.lane")


@dataclass
class LaneContext:
    """Per-run context shared by every lane in one sprint."""

    config: NamlConfig
    sprint: Sprint
    sprint_root: Path                # .naml/sprints/<id>/ resolved against repo
    lane_root: Path                  # parent dir for all worktrees
    log_dir: Path                    # where per-slice .log files land
    stop_after: str = "review"       # pr | review | merge — Phase 3 default = review
    overlap_findings: list[tuple[str, str, str, str]] = None  # set by Scheduler.preflight

    def __post_init__(self) -> None:
        if self.overlap_findings is None:
            self.overlap_findings = []


def _branch_name_for(sprint_id: str, slice_id: str) -> str:
    return f"naml/{sprint_id}/{slice_id}"


def _slice_log_path(log_dir: Path, sprint_id: str, slice_id: str) -> Path:
    return log_dir / sprint_id / f"{slice_id}.log"


def _collect_upstream_summaries(
    sprint_root: Path, slice_: Slice
) -> dict[str, str]:
    out: dict[str, str] = {}
    for dep in slice_.depends_on:
        body = state_mod.read_summary(sprint_root, dep)
        if body:
            out[dep] = body
    return out


def _pr_title(sprint: Sprint, slice_: Slice) -> str:
    return f"[{sprint.id}/{slice_.id}] {slice_.title}"


def _pr_body(
    sprint: Sprint,
    slice_: Slice,
    upstream_summaries: dict[str, str],
    overlap_findings: list[tuple[str, str, str, str]],
) -> str:
    pieces = [
        f"## Sprint\n\n`{sprint.id}` — {sprint.title}",
        f"\n## Slice\n\n`{slice_.id}` — {slice_.title}",
        f"\nType: `{slice_.type}`",
    ]
    if slice_.depends_on:
        pieces.append(f"\nDepends on: " + ", ".join(f"`{d}`" for d in slice_.depends_on))
    if slice_.touches:
        pieces.append("\nTouches: " + ", ".join(f"`{g}`" for g in slice_.touches))

    pieces.append("\n## Acceptance criteria\n\n" + _ac_from(slice_.prompt_body))

    if upstream_summaries:
        pieces.append("\n## Upstream context\n")
        for sid, body in upstream_summaries.items():
            pieces.append(f"\n### {sid}\n\n{body.strip()}\n")

    if overlap_findings:
        relevant = [
            (a, b, glob, action) for a, b, glob, action in overlap_findings
            if slice_.id in (a, b)
        ]
        if relevant:
            pieces.append("\n## Pre-flight serialisation notes\n")
            for a, b, glob, action in relevant:
                pieces.append(
                    f"- `{a}` → `{b}` (overlap `{glob}`, action: {action})"
                )

    pieces.append(
        "\n---\n"
        "Generated by [naml](https://github.com/YosifElessawi/naml) — slice from a sprint package."
    )
    return "".join(pieces)


def _ac_from(slice_body: str) -> str:
    """Extract the acceptance-criteria block from a slice body for the PR description."""
    lines = slice_body.splitlines()
    out: list[str] = []
    in_ac = False
    for line in lines:
        if line.strip().lower().startswith("## acceptance criteria"):
            in_ac = True
            continue
        if in_ac and line.startswith("## "):
            break
        if in_ac:
            out.append(line)
    body = "\n".join(out).strip()
    return body or "(see slice prompt)"


def _record_attempt(status: state_mod.SliceStatus, state_name: str) -> int:
    """Increment the per-state attempt counter and return the new count."""
    next_count = status.attempts.get(state_name, 0) + 1
    status.attempts[state_name] = next_count
    return next_count


def _transition(
    status: state_mod.SliceStatus,
    new_state: str,
    *,
    sprint_root: Path,
    detail: str = "",
) -> None:
    status.state = new_state
    status.record_transition(state=new_state, detail=detail)
    if detail:
        log.info("[%s] → %s (%s)", status.slice_id, new_state, detail)
    else:
        log.info("[%s] → %s", status.slice_id, new_state)
    state_mod.save_slice_status(sprint_root, status)


# --- the lane entry point ------------------------------------------------

def process_slice(slice_id: str, ctx: LaneContext) -> str:
    """Run one slice end-to-end. Returns the final state.

    The scheduler is told to mark the slice done/failed via the returned
    state. ``process_slice`` itself never raises out — failures are caught
    and recorded.
    """
    sprint = ctx.sprint
    cfg = ctx.config
    sprint_root = ctx.sprint_root
    slice_ = sprint.slice_by_id(slice_id)

    status = state_mod.load_slice_status(sprint_root, slice_id) or state_mod.SliceStatus(
        slice_id=slice_id
    )

    log_path = _slice_log_path(ctx.log_dir, sprint.id, slice_id)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        # ----- setup -----
        _transition(status, "setup", sprint_root=sprint_root)
        worktree = gitops.lane_worktree_path(
            lane_root=ctx.lane_root,
            repo_slug=cfg.repo,
            sprint_id=sprint.id,
            slice_id=slice_id,
        )
        gitops.worktree_add(
            worktree,
            repo_root=cfg.repo_root,
            base_branch=cfg.base_branch,
            symlinks=cfg.worktree_symlinks,
        )
        branch = _branch_name_for(sprint.id, slice_id)
        gitops.create_branch_from_base(
            branch, cwd=worktree, base_branch=cfg.base_branch
        )
        status.worktree = str(worktree)
        status.branch = branch

        # Reset attempts on fresh start.
        if not status.session_id:
            status.session_id = str(uuid.uuid4())

        # Compose prompt with upstream summaries.
        upstream = _collect_upstream_summaries(sprint_root, slice_)
        # The summary path is RELATIVE to the worktree's repo root, so the
        # agent writes it under <repo>/.naml/sprints/<sprint>/state/...
        # which lands inside the worktree on the slice branch. We then
        # forward the file's contents up to the canonical sprint_root after
        # the lane completes — see "post-work" below.
        summary_rel = (
            f".naml/sprints/{sprint.id}/{state_mod.STATE_DIRNAME}/"
            f"{state_mod.SUMMARY_FILENAME.format(slice_id=slice_id)}"
        )
        prompt_text = prompts.implementer_prompt(
            sprint=sprint,
            slice_=slice_,
            upstream_summaries=upstream,
            branch_name=branch,
            summary_path_relative=summary_rel,
        )

        # ----- work + gates loop -----
        _transition(status, "work", sprint_root=sprint_root)
        tokens_jsonl = state_mod.tokens_path(sprint_root, slice_id)
        result = run_implementer(
            prompt=prompt_text,
            session_id=status.session_id,
            log_path=log_path,
            cwd=worktree,
            claude_bin=cfg.claude_bin,
            claude_config_dir=cfg.claude_config_dir,
            cap_minutes=cfg.run_cap_minutes,
            resume=False,
            display_name=f"naml-{sprint.id}-{slice_id}",
            tokens_jsonl_path=tokens_jsonl,
            slice_id=slice_id,
            model_context_max=cfg.model_context_max,
        )
        if not _result_ok(result, status, sprint_root):
            return status.state

        gate_result = run_gates(
            cfg.gates,
            cwd=worktree,
            log_path=log_path,
        )
        retries_used = 0
        while not gate_result.passed and retries_used < cfg.max_retries:
            retries_used += 1
            _record_attempt(status, "work")
            state_mod.save_slice_status(sprint_root, status)
            retry_text = prompts.retry_prompt(
                failed_gate=gate_result.failed_gate or "?", tail=gate_result.tail
            )
            result = run_implementer(
                prompt=retry_text,
                session_id=status.session_id,
                log_path=log_path,
                cwd=worktree,
                claude_bin=cfg.claude_bin,
                claude_config_dir=cfg.claude_config_dir,
                cap_minutes=cfg.run_cap_minutes,
                resume=True,
                tokens_jsonl_path=tokens_jsonl,
                slice_id=slice_id,
                model_context_max=cfg.model_context_max,
            )
            if not _result_ok(result, status, sprint_root):
                return status.state
            gate_result = run_gates(
                cfg.gates, cwd=worktree, log_path=log_path
            )

        if not gate_result.passed:
            status.last_error = (
                f"gate '{gate_result.failed_gate}' failed after "
                f"{cfg.max_retries} retries"
            )
            _transition(status, "failed", sprint_root=sprint_root,
                        detail=status.last_error)
            return "failed"

        # ----- pull the summary forward to the canonical state dir -----
        # Implementer agents write the summary inside the worktree; we copy
        # it into the canonical sprint_root so downstream lanes can read it
        # without depending on the worktree still existing.
        worktree_summary = worktree / summary_rel
        if worktree_summary.is_file():
            state_mod.ensure_state_dir(sprint_root)
            target = state_mod.summary_path(sprint_root, slice_id)
            target.write_text(
                worktree_summary.read_text(encoding="utf-8"), encoding="utf-8"
            )
        else:
            # Not fatal — Phase 2 just notes it. Phase 3 may enforce.
            log.warning(
                "[%s] implementer did not write %s; downstream slices will see no upstream context",
                slice_id, summary_rel,
            )

        # ----- pr -----
        _transition(status, "pr", sprint_root=sprint_root)
        if not gitops.diff_has_changes(
            branch, cwd=worktree, base_branch=cfg.base_branch
        ):
            status.last_error = "no diff produced — slice work was empty"
            _transition(status, "failed", sprint_root=sprint_root,
                        detail=status.last_error)
            return "failed"

        gitops.push_branch(branch, cwd=worktree)
        title = _pr_title(sprint, slice_)
        body = _pr_body(sprint, slice_, upstream, ctx.overlap_findings)
        pr_url = gitops.create_pr(
            branch=branch,
            title=title,
            body=body,
            cwd=worktree,
            repo=cfg.repo,
            base_branch=cfg.base_branch,
            draft=False,
        )
        status.pr_url = pr_url
        _transition(status, states.PR, sprint_root=sprint_root,
                    detail=f"opened {pr_url}")

        if ctx.stop_after == "pr":
            return states.PR

        # ----- review -----
        return _drive_review_loop(
            ctx=ctx,
            sprint=sprint,
            slice_=slice_,
            worktree=worktree,
            branch=branch,
            log_path=log_path,
            upstream=upstream,
            status=status,
        )

    except Exception as exc:  # noqa: BLE001 — top-level lane safety net
        status.last_error = f"{type(exc).__name__}: {exc}"
        _transition(
            status, "failed", sprint_root=sprint_root, detail=status.last_error
        )
        log.exception("[%s] lane failed", slice_id)
        return "failed"


def _result_ok(
    result: RunResult, status: state_mod.SliceStatus, sprint_root: Path
) -> bool:
    """Translate a Claude run result into a stay-in-flight / fail decision."""
    if result.timed_out:
        status.last_error = "implementer agent hit the run cap"
        _transition(status, "failed", sprint_root=sprint_root, detail=status.last_error)
        return False
    if not result.completed:
        status.last_error = f"implementer exited unexpectedly (code {result.exit_code})"
        _transition(status, "failed", sprint_root=sprint_root, detail=status.last_error)
        return False
    if result.exit_code != 0:
        status.last_error = f"implementer exit code {result.exit_code}"
        _transition(status, "failed", sprint_root=sprint_root, detail=status.last_error)
        return False
    return True


def _drive_review_loop(
    *,
    ctx: LaneContext,
    sprint: Sprint,
    slice_: Slice,
    worktree: Path,
    branch: str,
    log_path: Path,
    upstream: dict[str, str],
    status: state_mod.SliceStatus,
) -> str:
    """Run the review state up to ``states.RETRY_CAPS[REVIEW]`` attempts.

    Verdict semantics:
    - ``LGTM``            → state = ``review_passed``. Scheduler treats as done.
    - ``REQUEST_CHANGES`` → resume implementer with the review text. Push
                            again. Loop until the cap.
    - ``ABANDON``         → state = ``needs_human_review``. Scheduler marks
                            slice failed so dependents are blocked.
    - ``UNKNOWN``         → treat as REQUEST_CHANGES with no actionable
                            text, but eat one retry attempt (no infinite loop
                            if the reviewer never emits a verdict line).
    """
    cfg = ctx.config
    sprint_root = ctx.sprint_root
    cap = states.retry_cap(states.REVIEW)
    tokens_jsonl = state_mod.tokens_path(sprint_root, slice_.id)

    for attempt in range(1, cap + 1):
        _record_attempt(status, states.REVIEW)
        _transition(
            status,
            states.REVIEW,
            sprint_root=sprint_root,
            detail=f"reviewer attempt {attempt}/{cap}",
        )

        # Fetch the fresh diff for the reviewer.
        try:
            diff = gitops.pr_diff(branch, cwd=worktree, repo=cfg.repo)
        except gitops.GhError as exc:
            status.last_error = f"could not fetch PR diff: {exc}"
            _transition(status, states.FAILED, sprint_root=sprint_root,
                        detail=status.last_error)
            return states.FAILED

        review_prompt = prompts.reviewer_prompt(
            sprint=sprint,
            slice_=slice_,
            pr_url=status.pr_url,
            diff=diff,
            upstream_summaries=upstream,
        )
        review_result = run_reviewer(
            prompt=review_prompt,
            log_path=log_path,
            cwd=worktree,
            claude_bin=cfg.claude_bin,
            claude_config_dir=cfg.claude_config_dir,
            cap_minutes=max(10, cfg.run_cap_minutes // 2),
        )
        if review_result.timed_out:
            status.last_error = "reviewer agent hit the run cap"
            _transition(status, states.FAILED, sprint_root=sprint_root,
                        detail=status.last_error)
            return states.FAILED

        verdict = parse_verdict(review_result.final_text)
        status.review_verdict = verdict
        state_mod.save_slice_status(sprint_root, status)
        log.info("[%s] reviewer verdict: %s", slice_.id, verdict)

        if verdict == "LGTM":
            _transition(status, states.REVIEW_PASSED, sprint_root=sprint_root,
                        detail="auto-review LGTM")
            return states.REVIEW_PASSED

        if verdict == "ABANDON":
            status.last_error = "reviewer abandoned — change unsalvageable"
            _transition(status, states.NEEDS_HUMAN_REVIEW,
                        sprint_root=sprint_root, detail=status.last_error)
            return states.NEEDS_HUMAN_REVIEW

        # REQUEST_CHANGES or UNKNOWN → if this was the last attempt, escalate.
        if attempt >= cap:
            status.last_error = (
                f"review retries exhausted after {cap} attempts; final verdict {verdict}"
            )
            _transition(status, states.NEEDS_HUMAN_REVIEW,
                        sprint_root=sprint_root, detail=status.last_error)
            return states.NEEDS_HUMAN_REVIEW

        # Resume the implementer in its original session with the review text.
        _transition(status, states.WORK, sprint_root=sprint_root,
                    detail=f"applying review (attempt {attempt})")
        fix_prompt = prompts.request_changes_prompt(
            review_text=review_result.final_text,
            pr_url=status.pr_url,
        )
        impl_result = run_implementer(
            prompt=fix_prompt,
            session_id=status.session_id,
            log_path=log_path,
            cwd=worktree,
            claude_bin=cfg.claude_bin,
            claude_config_dir=cfg.claude_config_dir,
            cap_minutes=cfg.run_cap_minutes,
            resume=True,
            tokens_jsonl_path=tokens_jsonl,
            slice_id=slice_.id,
            model_context_max=cfg.model_context_max,
        )
        if not _result_ok(impl_result, status, sprint_root):
            return status.state

        # Re-run gates so we don't push known-bad code back to the PR.
        gate_result = run_gates(cfg.gates, cwd=worktree, log_path=log_path)
        retries = 0
        while not gate_result.passed and retries < cfg.max_retries:
            retries += 1
            retry_text = prompts.retry_prompt(
                failed_gate=gate_result.failed_gate or "?", tail=gate_result.tail
            )
            impl_result = run_implementer(
                prompt=retry_text,
                session_id=status.session_id,
                log_path=log_path,
                cwd=worktree,
                claude_bin=cfg.claude_bin,
                claude_config_dir=cfg.claude_config_dir,
                cap_minutes=cfg.run_cap_minutes,
                resume=True,
                tokens_jsonl_path=tokens_jsonl,
                slice_id=slice_.id,
                model_context_max=cfg.model_context_max,
            )
            if not _result_ok(impl_result, status, sprint_root):
                return status.state
            gate_result = run_gates(cfg.gates, cwd=worktree, log_path=log_path)

        if not gate_result.passed:
            status.last_error = (
                f"gate '{gate_result.failed_gate}' failed during review fix loop"
            )
            _transition(status, states.FAILED, sprint_root=sprint_root,
                        detail=status.last_error)
            return states.FAILED

        # Re-push (gh PR auto-updates the existing PR on the same branch).
        if not gitops.diff_has_changes(
            branch, cwd=worktree, base_branch=cfg.base_branch
        ):
            # The implementer claimed DONE but no new commits — escalate.
            status.last_error = "implementer reported DONE but no new diff after review fix"
            _transition(status, states.NEEDS_HUMAN_REVIEW,
                        sprint_root=sprint_root, detail=status.last_error)
            return states.NEEDS_HUMAN_REVIEW
        gitops.push_branch(branch, cwd=worktree)

    # Shouldn't reach here — the loop above always returns. Defensive.
    status.last_error = "review loop exited without verdict"
    _transition(status, states.NEEDS_HUMAN_REVIEW, sprint_root=sprint_root,
                detail=status.last_error)
    return states.NEEDS_HUMAN_REVIEW


def cleanup_worktree(slice_status: state_mod.SliceStatus, *, repo_root: Path) -> None:
    """Best-effort: drop the lane's worktree once the slice has finished.

    Called by ``naml run`` after the scheduler reports completion. Idempotent.
    """
    if not slice_status.worktree:
        return
    path = Path(slice_status.worktree)
    if not path.exists():
        return
    gitops.worktree_remove(path, repo_root=repo_root)
